import java.util.HashMap;
import java.util.Set;

public class MuseHashMap {
    public String trackListMap() {
        HashMap<String, String> trackList = new HashMap<String, String>();
        trackList.put("Knights of Cydonia", 
            "Come ride with me"
            + "Through the veins of history"
            + "I'll show you a God"
            + "Falls asleep on the job"
            + "And how can we win,"
            + "When fools can be kings"
            + "Don't waste your time"
            + "Or time will waste you"
            + "No one's going to take me alive"
            + "Time has come to make things right"
            + "You and I must fight for our rights"
            + "You and I must fight to survive"
            + "No one's going to take me alive"
            + "Time has come to make things right"
            + "You and I must fight for our rights"
            + "You and I must fight to survive"
            + "No one's going to take me alive"
            + "Time has come to make things right"
            + "You and I must fight for our rights"
            + "You and I must fight to survive");
        trackList.put("Hysteria", 
            "It's bugging me"
            + "Grating me"
            + "And twisting me around"
            + "Yeah I'm endlessly"
            + "Caving in"
            + "And turning inside out"
            + "'Cause I want it now"
            + "I want it now"
            + "Give me your heart and your soul"
            + "And I'm breaking out"
            + "I'm breaking out"
            + "Last chance to lose control"
            + "Yeah it's holding me"
            + "Morphing me"
            + "And forcing me to strive"
            + "To be endlessly"
            + "Caving in"
            + "And dreaming I'm alive"
            + "'Cause I want it now"
            + "I want it now"
            + "Give me your heart and your soul"
            + "I'm not breaking down"
            + "I'm breaking out"
            + "Lace chance to lose control"
            + "And I want you now"
            + "I want you now"
            + "I feel my heart implode"
            + "And I'm breaking out"
            + "Escaping now"
            + "Feeling my faith erode");
        trackList.put("Uprising", 
            "The paranoia is in bloom, the P-R"
            + "Transmissions will resume"
            + "They'll try to push drugs"
            + "That keep us all dumbed down and hope that"
            + "We will never see the truth around"
            + "(So come on)"
            + "Another promise, another scene,"
            + "Another package lie to keep us trapped in greed"
            + "With all the green belts wrapped around our minds"
            + "And endless red tape to keep the truth confined"
            + "(So come on)"
            + "They will not force us"
            + "They will stop degrading us"
            + "They will not control us"
            + "We will be victorious "
            + "(So come on)"
            + "Interchanging mind control"
            + "Come let the revolution take its toll if you could"
            + "Flick a switch and open your third eye, you'd see that"
            + "We should never be afraid to die"
            + "(So come on)"
            + "Rise up and take the power back, it's time that"
            + "The fat cats had a heart attack, you know that"
            + "Their time is coming to an end"
            + "We have to unify and watch our flag ascend"
            + "(So come on)"
            + "They will not force us"
            + "They will stop degrading us"
            + "They will not control us"
            + "We will be victorious"
            + "(So come on)"
            + "Hey, hey, hey, hey"
            + "Hey, hey, hey, hey"
            + "Hey, hey, hey, hey"
            + "They will not force us"
            + "They will stop degrading us"
            + "They will not control us"
            + "We will be victorious"
            + "(So come on)"
            + "Hey, hey, hey, hey");
        trackList.put("Citizen Erased", 
            "Break me in, teach us to cheat"
            + "And to lie, cover up"
            + "What shouldn't be shared"
            + "And the truth's unwinding"
            + "Scraping away at my mind"
            + "Please stop asking me to describe"
            + "For one moment"
            + "I wish you'd hold your stage"
            + "With no feelings at all"
            + "Open-minded"
            + "I'm sure I used to be so free"
            + "Self-expressed, exhausting for all"
            + "To see and to be"
            + "What you want and what you need"
            + "The truth's unwinding"
            + "Scraping away at my mind"
            + "Please stop asking me to describe"
            + "For one moment"
            + "I wish you'd hold your stage"
            + "With no feelings at all"
            + "Open-minded"
            + "I'm sure I used to be so free"
            + "For one moment"
            + "I wish you'd hold your stage"
            + "With no feelings at all"
            + "Open-minded"
            + "I'm sure I used to be so free"
            + "Wash me away"
            + "Clean your body of me"
            + "Erase all the memories"
            + "They will only bring us pain"
            + "And I've seen, all I'll ever need");

        String song = trackList.get("Hysteria");
        System.out.println(song);
        System.out.println();
        Set<String> tracks = trackList.keySet();
        for(String track : tracks) {
            System.out.println(track +" : "+ trackList.get(track));
            System.out.println();
        }
        return null;
    }
}